//! TurboMCP v4 codegen: MCP schema JSON → checked-in Rust wire types via typify.
//!
//! ```text
//! turbomcp4-codegen <input-schema.json> <output.rs> [label]
//! ```
//!
//! Applies the [`normalize`] `allOf`-flattening pre-pass (AUDIT_FINDINGS.md F14)
//! so both the `2025-11-25` and `DRAFT-2026-v1` schemas generate compiling Rust.
//! Output is checked in and reviewed on each spec update; this binary is not in
//! the user dependency graph.
#![forbid(unsafe_code)]

mod normalize;

use anyhow::{Context, Result, bail};
use typify::{TypeSpace, TypeSpaceSettings};

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 3 {
        bail!("usage: turbomcp4-codegen <input-schema.json> <output.rs> [label]");
    }
    let input = &args[1];
    let output = &args[2];
    let label = args.get(3).map_or("an MCP schema", String::as_str);

    let raw = std::fs::read_to_string(input).with_context(|| format!("reading schema {input}"))?;
    let mut value: serde_json::Value =
        serde_json::from_str(&raw).with_context(|| format!("parsing {input} as JSON"))?;

    // Normalize before handing to typify (F14).
    normalize::flatten_all_of(&mut value);

    let schema: schemars::schema::RootSchema =
        serde_json::from_value(value).context("interpreting normalized JSON as a RootSchema")?;

    let mut settings = TypeSpaceSettings::default();
    settings
        .with_struct_builder(false)
        // BTreeMap for deterministic, stable-diff output; `alloc` (not `std`) so
        // the map path in `skip_serializing_if = "..."` attribute strings is
        // no_std-resolvable.
        .with_map_type("::alloc::collections::BTreeMap");

    let mut type_space = TypeSpace::new(&settings);
    type_space
        .add_root_schema(schema)
        .context("typify schema conversion failed")?;

    let intro = "#![allow(clippy::all)]\n\
#![allow(clippy::pedantic)]\n\
#![allow(missing_docs)]\n\
#![allow(unused_imports)]\n";
    // typify relies on the std prelude for a few unqualified names (`String`,
    // `ToString`, `Vec`, …). Under `no_std` the `core` prelude lacks them, so
    // bring them in from `alloc` (only when std is off — the host crate provides
    // `extern crate alloc`). All other paths are already remapped to alloc/core.
    let no_std_prelude = "#[cfg(not(feature = \"std\"))]\n\
use ::alloc::{borrow::ToOwned, boxed::Box, format, string::{String, ToString}, vec, vec::Vec};\n";
    let body = format!("{intro}\n{no_std_prelude}\n{}", type_space.to_stream());
    let file = syn::parse_file(&body).context("parsing generated tokens as a Rust file")?;
    let pretty = to_no_std(&prettyplease::unparse(&file));

    let header = format!(
        "//! @generated by turbomcp4-codegen from {label}. DO NOT EDIT.\n\
//!\n\
//! Regenerate via `just codegen`. Normalization: allOf-flatten (F14).\n\
//! Source schema path at generation time: {input}\n\n"
    );

    std::fs::write(output, format!("{header}{pretty}"))
        .with_context(|| format!("writing {output}"))?;

    eprintln!(
        "turbomcp4-codegen: wrote {output} ({} lines) from {input}",
        pretty.lines().count()
    );
    Ok(())
}

/// Rewrite typify's `::std::` absolute paths to `::alloc::`/`::core::` so the
/// generated module is `no_std` (the foundation/protocol crates are wasm-
/// portable). Only the segments typify actually emits are remapped; with
/// `map_type = BTreeMap` there are no `std`-only collection types. A final
/// blanket `::std::` → `::core::` catches the rest (all remaining segments
/// have `core` equivalents). The host crate provides `extern crate alloc`.
fn to_no_std(src: &str) -> String {
    // Segments that live in `alloc`, not `core`.
    const ALLOC_SEGMENTS: [&str; 8] = [
        "string",
        "vec",
        "borrow",
        "collections",
        "boxed",
        "rc",
        "sync",
        "ffi",
    ];
    let mut out = src.to_string();
    for seg in ALLOC_SEGMENTS {
        out = out.replace(&format!("::std::{seg}::"), &format!("::alloc::{seg}::"));
        // typify also stringifies paths with spaces inside serde attribute
        // strings (e.g. `skip_serializing_if = ":: std :: collections :: …"`).
        out = out.replace(
            &format!(":: std :: {seg} ::"),
            &format!(":: alloc :: {seg} ::"),
        );
    }
    // Everything still `::std::*` / `:: std ::` resolves under `core`.
    out = out.replace("::std::", "::core::");
    out = out.replace(":: std ::", ":: core ::");

    // typify's nested `mod error` fixture uses unqualified `String`/`ToOwned`
    // from the std prelude; the file-level prelude `use` does not reach into it.
    out.replace(
        "pub mod error {",
        "pub mod error {\n    #[cfg(not(feature = \"std\"))]\n    #[allow(unused_imports)]\n    use ::alloc::{borrow::ToOwned, string::String};",
    )
}
